127 auto attendant functionality
Jordan-Prescott/odins_spear pull request #128
Opened 2024-10-23 15:01 UTC by LivCurtis

Added new methods:

- get.auto_attendant_user
- get.auto_attendant_submenus
- get.auto_attendant_submenu_usage
- post.auto_attendant
- post.auto_attendant_remove_user
- post.auto_attendant_submenu
- del.auto_attendant
- del.auto_attendant_submenu

2024-10-28 11:39 UTC, Jordan-Prescott requested changes
Some changes regarding the payload Liv in the post method.

2024-10-28 11:39 UTC, Jordan-Prescott commented on odins_spear/methods/post.py
> +
This needs update the existing payload otherwise your overwriting whatever is passed in the param. 

Example:
payload['groupId'] = group_id

2024-10-28 11:39 UTC, Jordan-Prescott commented on odins_spear/methods/post.py
> +
Additionally things where you have hard coded like  "nameDialingEntries":"LastName + FirstName" we need to check this is empty and not passed in by the user before editing.

2024-10-29 08:48 UTC, LivCurtis commented on odins_spear/methods/post.py
> +
I've resolved this and pushed new commits.

2024-10-29 15:08 UTC, Jordan-Prescott approved these changes
All good, nice work Liv!!

2024-10-29 15:08 UTC, merged