Eva bulider methods
Jordan-Prescott/odins_spear pull request #50
Opened 2024-06-18 13:49 UTC by LivCurtis

Methods added to put.py:
service_providers_trunk_group_call_capacity 
group_device
group_trunk_groups_call_capacity
user_call_processing_policy 
group_trunk_group

Methods added to post.py:
group_hunt_group 
group_trunk_group

2024-06-19 07:39 UTC, Jordan-Prescott commented on odins_spear/methods/post.py
> +    def group_device(self, service_provider_id: str, group_id: str, device_name: str, device_type: str):
Missing a data argument here. Looking at the API docs there are many more fields that can be send in the request that we currently here dont allow the user to utilise.

Docs: https://doc.odinapi.net/#aeef85c0-376d-4d3c-b1a7-f37d90fcb872

2024-06-19 07:48 UTC, Jordan-Prescott commented on odins_spear/methods/post.py
> +    def group_hunt_group(self, service_provider_id: str, group_id: str, service_user_id: str, clid_first_name: str, clid_last_name:str, extension: str, policy: str ="Regular"):
- Same as above there are more options in the payload and we dont give the user access to that. 
- I like the default option in the policy
- The list of agents here I think would be a great thing to include because most of the time hunt groups are built for users to be added
- In the return you specify JSON but its a Python Dict

2024-06-19 07:50 UTC, Jordan-Prescott commented on odins_spear/methods/post.py
> +    def group_trunk_group(self, service_provider_id: str, group_id: str, trunk_name: str, max_active_calls: int):
- Same as above we need to add in data as an argument 
- When we have the data we can adjust how we make sure the needed data is in the payload

2024-06-19 07:57 UTC, Jordan-Prescott commented on odins_spear/methods/put.py
> +    def user_call_processing_policy(self, user_id: str, updates: dict):
- line 470 it has userID I think this should be userId
- In return this should be Dict not JSON

2024-06-19 07:59 UTC, Jordan-Prescott commented on odins_spear/methods/put.py
> +    def group_trunk_groups_call_capacity(self, service_provider_id: str, group_id: str, max_active_calls: int):
- Looking at the docs I think we are missing a couple of options here we could include/ give the updates argument

https://doc.odinapi.net/#db692781-d520-4f88-89f8-2ec160652c55

2024-06-19 08:01 UTC, Jordan-Prescott commented on odins_spear/methods/put.py
- Are we missing a return here?

2024-06-19 08:03 UTC, Jordan-Prescott commented on odins_spear/methods/put.py
> +            JSON: Updated TG profile.
- Return should be None checking the docs all that is returned is '[]' which is basically useless so return None. This may be the same for the other methods you have added.
- My OCD kicking in we need to remove the unnecessary spaces

2024-06-19 08:07 UTC, Jordan-Prescott commented on odins_spear/methods/put.py
> +            JSON: Updated TG profile.
The update is adding in SP in brackets

2024-06-19 08:09 UTC, Jordan-Prescott commented on odins_spear/methods/post.py
> +        data = {
This is a python dict not JSON so we need to update for that.

2024-06-21 13:49 UTC, LivCurtis commented on odins_spear/methods/post.py
> +    def group_hunt_group(self, service_provider_id: str, group_id: str, service_user_id: str, clid_first_name: str, clid_last_name:str, extension: str, policy: str ="Regular"):
I have added payload and agents as optional arguments to this method and updated the Return.

2024-06-21 14:32 UTC, LivCurtis commented on odins_spear/methods/post.py
> +        data = {
I have updated the Return to say "None: This method does not return any specific value." as when I tested in sandbox file of VSC there was no output.

2024-06-21 14:46 UTC, LivCurtis commented on odins_spear/methods/put.py
> +    def user_call_processing_policy(self, user_id: str, updates: dict):
Nice spot, I've just fixed that and tested it - all good now. 
I've also updated the Return to be None

2024-06-21 15:23 UTC, LivCurtis commented on odins_spear/methods/put.py
We are indeed, I have just added this in :)

2024-06-24 09:29 UTC, Jordan-Prescott requested changes
Please updated the commented

2024-06-25 13:31 UTC, merged