Fixed put.group_hunt_group method
Jordan-Prescott/odins_spear pull request #80
Opened 2024-07-26 09:32 UTC by LivCurtis

Assigned an empty dict to "serviceInstanceProfile" as this needs to exist for the method to work. Also corrected a couple of things in the docstring.

2024-07-26 10:41 UTC, Jordan-Prescott commented on odins_spear/methods/put.py
>      def group_hunt_group(self, service_provider_id: str, group_id: str, hunt_group_user_id: str, updates: dict):
Change hunt_group_user_id to service_user_id in these args.

2024-07-26 10:52 UTC, Jordan-Prescott requested changes
Adjust for comments please.

2024-07-26 10:52 UTC, Jordan-Prescott commented on odins_spear/methods/put.py
> +        updates["serviceUserId"] = hunt_group_user_id
Should match new argument

2024-07-26 10:52 UTC, Jordan-Prescott commented on odins_spear/methods/put.py
> +        updates["serviceInstanceProfile"] = {}
Check if this is in the updates otherwise here you will override it

2024-07-26 13:47 UTC, LivCurtis reviewed
Have made the suggested changes.

2024-07-26 13:47 UTC, LivCurtis commented on odins_spear/methods/put.py
>      def group_hunt_group(self, service_provider_id: str, group_id: str, hunt_group_user_id: str, updates: dict):
Done :)

2024-07-26 13:47 UTC, LivCurtis commented on odins_spear/methods/put.py
> +        updates["serviceUserId"] = hunt_group_user_id
Done :)

2024-07-26 13:47 UTC, LivCurtis commented on odins_spear/methods/put.py
> +        updates["serviceInstanceProfile"] = {}
Done :)

2024-08-12 09:26 UTC, Jordan-Prescott approved these changes
All looks good, nice work Liv!

2024-08-12 09:26 UTC, merged